### ISSUE TITLE
Bug: TypeError: type Tensor doesn't define __round__ method

### ISSUE THREAD

**Issue by higuhigu-lb** [docling-project/docling-ibm-models#62]
### Bug

I encounter the following error when running demo script for layout parser.

```
Traceback (most recent call last):
  File "/Users/s_higuchi/.pyenv/versions/3.10.14/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/s_higuchi/.pyenv/versions/3.10.14/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/s_higuchi/project/docling_debug/docling-ibm-models/demo/demo_layout_predictor.py", line 133, in <module>
    main(args)
  File "/Users/s_higuchi/project/docling_debug/docling-ibm-models/demo/demo_layout_predictor.py", line 107, in main
    demo(logger, artifact_path, num_threads, img_dir, viz_dir)
  File "/Users/s_higuchi/project/docling_debug/docling-ibm-models/demo/demo_layout_predictor.py", line 55, in demo
    round(pred["l"]),
TypeError: type Tensor doesn't define __round__ method
```

### Steps to reproduce

```
python -m demo.demo_layout_predictor -i tests/test_data/samples -v viz/
```

### Docling-ibm-models version

Version: 2.0.7

### Python version

Python 3.10.14

**Comment by higuhigu-lb** [comment]
The round() method is not applicable to tensors.
[demo_layout_predictor.py](https://github.com/DS4SD/docling-ibm-models/blob/204c3d1e0f50389dc3ffbed59b8772647b0d44e7/demo/demo_layout_predictor.py#L55) needs modification.

```
box = [
    int(pred["l"].round().item()),
    int(pred["t"].round().item()),
    int(pred["r"].round().item()),
    int(pred["b"].round().item()),
]
```

**Comment by cau-git** [comment]
The layout model and its demo script have since been removed from this repo (#184). Closing since this no longer applies here.
